# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stormapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(to='stormapp.Actor'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genders',
            field=models.ManyToManyField(to='stormapp.Gender'),
        ),
        migrations.AddField(
            model_name='movie',
            name='releated_filmes',
            field=models.ManyToManyField(related_name='_movie_releated_filmes_+', to='stormapp.Movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='sinopse',
            field=models.TextField(max_length=2000),
        ),
    ]
