# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stormapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='picture',
            field=models.ImageField(default=b'', upload_to=b'static/stormapp/movie_pictures'),
        ),
    ]
