# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 23:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import stormapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('stormapp', '0002_movie_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 12, 23, 43, 56, 693148, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='picture',
            field=models.ImageField(default=b'', upload_to=stormapp.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='movie',
            name='sinopse',
            field=models.TextField(max_length=800),
        ),
    ]
