# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stormapp', '0005_auto_20160412_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=b'stormapp/static/stormapp/movie_pictures'),
        ),
    ]
